/*
 * ClamWin Free Antivirus — CWConfig implementation
 *
 * Copyright (c) 2004-2026 ClamWin Pty Ltd
 * License: GPLv2
 */

#include "cw_config.h"
#include "cw_gui_shared.h"   /* for CW_INI_SECTION_* defines */
#include "cw_text_conv.h"

#include <stdio.h>
#include <string.h>

/* ─── Section names (same as legacy Python ClamWin) ─────────── */

static const TCHAR* SEC_CLAMAV   = TEXT("ClamAV");
static const TCHAR* SEC_UPDATES  = TEXT("Updates");
static const TCHAR* SEC_PROXY    = TEXT("Proxy");
static const TCHAR* SEC_SCHEDULE = TEXT("Schedule");
static const TCHAR* SEC_ALERTS   = TEXT("EmailAlerts");
static const TCHAR* SEC_UI       = TEXT("UI");

static std::string normalizeFilterPatterns(const std::string& raw)
{
    if (raw == "*.dbx|CLAMWIN_SEP|bb|CLAMWIN_SEP|st")
        return "*.dbx|CLAMWIN_SEP|*.tbb|CLAMWIN_SEP|*.pst";
    return raw;
}

/* ─── Constructor: apply defaults ────────────────────────────── */

CWConfig::CWConfig()
{
    defaults();
}

/* ─── Defaults ──────────────────────────────────────────────── */

void CWConfig::defaults()
{
    TCHAR exedir[MAX_PATH];
    GetModuleFileName(NULL, exedir, MAX_PATH);
    TCHAR* slash = _tcsrchr(exedir, TEXT('\\'));
    if (slash) *(slash + 1) = '\0';
    std::string exedirStr = CW_ToNarrow(exedir);

    TCHAR profile[MAX_PATH];
    DWORD profileLen = GetEnvironmentVariable(TEXT("USERPROFILE"), profile, MAX_PATH);
    if (profileLen > 0 && profileLen < MAX_PATH)
    {
        std::string profileRoot = CW_ToNarrow(profile) + "\\.clamwin";
        databasePath   = profileRoot + "\\db";
        quarantinePath = profileRoot + "\\Quarantine";
        scanLogFile    = profileRoot + "\\ClamScan.log";
        updateLogFile  = profileRoot + "\\FreshClam.log";
    }
    else
    {
        databasePath   = exedirStr + "db";
        quarantinePath = exedirStr + "Quarantine";
        scanLogFile    = exedirStr + "ClamScan.log";
        updateLogFile  = exedirStr + "FreshClam.log";
    }

    iniPath         = defaultIniPath();

    scanRecursive   = true;
    scanArchives    = true;
    scanOle2        = true;
    scanMail        = false;
    infectedAction  = 0;
    infectedOnly    = false;
    maxScanSizeMb   = 150;
    maxFileSizeMb   = 100;
    maxFiles        = 500;
    maxDepth        = 50;

    dbMirror        = "database.clamav.net";
    updateOnStartup = false;
    checkVersion    = true;

    proxyEnabled    = false;
    proxyHost       = "";
    proxyPort       = 3128;
    proxyUser       = "";
    proxyPass       = "";

    emailEnabled    = false;
    emailFrom = emailTo = emailSmtp = "";

    scanScheduled   = false;
    scanHour        = 22;
    scanMinute      = 0;
    scanFrequency   = 0;
    scanDay         = 0;
    scanPath        = "";
    scanDescription = "";
    scanMemory      = false;
    scanRunMissed   = true;
    scanLastRunTime = 0;
    updateScheduled = true;
    updateHour      = 4;
    updateMinute    = 0;
    updateFrequency = 0;
    updateRunMissed = true;
    updateLastRunTime = 0;
    schedulerDebug  = false;

    closeOnExit     = false;
    trayNotify      = true;
    priority        = "n";

    includePatterns = "";
    excludePatterns = "*.dbx|CLAMWIN_SEP|*.tbb|CLAMWIN_SEP|*.pst";
}

/* ─── Default INI path ──────────────────────────────────────── */

std::string CWConfig::defaultIniPath()
{
    TCHAR profile[MAX_PATH];
    DWORD len = GetEnvironmentVariable(TEXT("USERPROFILE"), profile, MAX_PATH);
    if (len > 0 && len < MAX_PATH)
    {
        return CW_ToNarrow(profile) + "\\.clamwin\\ClamWin.conf";
    }
    /* Fallback: same directory as executable */
    TCHAR exedir[MAX_PATH];
    GetModuleFileName(NULL, exedir, MAX_PATH);
    TCHAR* slash = _tcsrchr(exedir, TEXT('\\'));
    if (slash) *(slash + 1) = '\0';
    return CW_ToNarrow(exedir) + "ClamWin.conf";
}

/* ─── freshclam.conf path ────────────────────────────────────── */

std::string CWConfig::freshclamConfPath() const
{
    /* Same directory as iniPath, but with filename freshclam.conf */
    size_t slash = iniPath.rfind('\\');
    if (slash != std::string::npos)
        return iniPath.substr(0, slash + 1) + "freshclam.conf";
    return "freshclam.conf";
}

/* ─── Write freshclam.conf ───────────────────────────────────── */

bool CWConfig::writeFreshclamConf() const
{
    std::string path = freshclamConfPath();

    /* Ensure the parent directory exists */
    std::string dir = path;
    size_t slash = dir.rfind('\\');
    if (slash != std::string::npos)
    {
        dir.resize(slash);
        std::basic_string<TCHAR> tDir = CW_ToT(dir);
        CreateDirectory(tDir.c_str(), NULL);
    }

    FILE* f = fopen(path.c_str(), "w");
    if (!f)
        return false;

    fprintf(f, "# freshclam.conf — generated by ClamWin\n");
    fprintf(f, "# Do not edit: overwritten when preferences are saved.\n\n");

    /* Mirror */
    fprintf(f, "DatabaseMirror %s\n",
            dbMirror.empty() ? "database.clamav.net" : dbMirror.c_str());

    /* Database directory */
    if (!databasePath.empty())
        fprintf(f, "DatabaseDirectory %s\n", databasePath.c_str());

    /* Update log */
    if (!updateLogFile.empty())
        fprintf(f, "UpdateLogFile %s\n", updateLogFile.c_str());

    /* Proxy */
    if (proxyEnabled && !proxyHost.empty())
    {
        fprintf(f, "HTTPProxyServer %s\n", proxyHost.c_str());
        fprintf(f, "HTTPProxyPort %d\n",   proxyPort);
        if (!proxyUser.empty())
            fprintf(f, "HTTPProxyUsername %s\n", proxyUser.c_str());
        if (!proxyPass.empty())
            fprintf(f, "HTTPProxyPassword %s\n", proxyPass.c_str());
    }

    fclose(f);
    return true;
}

/* ─── Load ──────────────────────────────────────────────────── */

bool CWConfig::load(const std::string& path)
{
    defaults();

    if (!path.empty())
        iniPath = path;

    {
        std::basic_string<TCHAR> tIniPath = CW_ToT(iniPath);
        if (GetFileAttributes(tIniPath.c_str()) == INVALID_FILE_ATTRIBUTES)
        {
            /* Keep freshclam.conf in sync with the default/profile config path
             * even when ClamWin.conf does not exist yet. */
            writeFreshclamConf();
            return false;  /* no file — defaults already applied */
        }
    }

    databasePath   = getStr(SEC_CLAMAV, TEXT("Database"),      databasePath);
    scanRecursive  = getInt(SEC_CLAMAV, TEXT("ScanRecursive"), scanRecursive) != 0;
    scanArchives   = getInt(SEC_CLAMAV, TEXT("ScanArchives"),  scanArchives)  != 0;
    scanOle2       = getInt(SEC_CLAMAV, TEXT("ScanOle2"),      scanOle2)      != 0;
    scanMail       = getInt(SEC_CLAMAV, TEXT("ScanMail"),      scanMail)      != 0;
    infectedAction = getInt(SEC_CLAMAV, TEXT("InfectedAction"), infectedAction);
    infectedOnly   = getInt(SEC_CLAMAV, TEXT("InfectedOnly"),   infectedOnly)   != 0;
    maxScanSizeMb  = getInt(SEC_CLAMAV, TEXT("MaxScanSize"),   maxScanSizeMb);
    maxFileSizeMb  = getInt(SEC_CLAMAV, TEXT("MaxFileSize"),   maxFileSizeMb);
    maxFiles       = getInt(SEC_CLAMAV, TEXT("MaxFiles"),      maxFiles);
    maxDepth       = getInt(SEC_CLAMAV, TEXT("MaxRecursion"),  maxDepth);
    quarantinePath = getStr(SEC_CLAMAV, TEXT("Quarantine"),    quarantinePath);
    scanLogFile    = getStr(SEC_CLAMAV, TEXT("LogFile"),       scanLogFile);
    priority       = getStr(SEC_CLAMAV, TEXT("Priority"),      priority);

    dbMirror        = getStr(SEC_UPDATES, TEXT("DBMirror"),        dbMirror);
    updateLogFile   = getStr(SEC_UPDATES, TEXT("UpdateLog"),       updateLogFile);
    updateOnStartup = getInt(SEC_UPDATES, TEXT("UpdateOnStartup"), updateOnStartup) != 0;
    checkVersion    = getInt(SEC_UPDATES, TEXT("CheckVersion"),    checkVersion)    != 0;

    proxyEnabled = getInt(SEC_PROXY, TEXT("Enabled"),  proxyEnabled) != 0;
    proxyHost    = getStr(SEC_PROXY, TEXT("Host"),     proxyHost);
    proxyPort    = getInt(SEC_PROXY, TEXT("Port"),     proxyPort);
    proxyUser    = getStr(SEC_PROXY, TEXT("User"),     proxyUser);
    proxyPass    = getStr(SEC_PROXY, TEXT("Password"), proxyPass);

    emailEnabled = getInt(SEC_ALERTS, TEXT("Enabled"), emailEnabled) != 0;
    emailFrom    = getStr(SEC_ALERTS, TEXT("From"),    emailFrom);
    emailTo      = getStr(SEC_ALERTS, TEXT("To"),      emailTo);
    emailSmtp    = getStr(SEC_ALERTS, TEXT("SMTP"),    emailSmtp);

    scanScheduled   = getInt(SEC_SCHEDULE, TEXT("ScanEnabled"),    scanScheduled)   != 0;
    scanHour        = getInt(SEC_SCHEDULE, TEXT("ScanHour"),       scanHour);
    scanMinute      = getInt(SEC_SCHEDULE, TEXT("ScanMinute"),     scanMinute);
    scanFrequency   = getInt(SEC_SCHEDULE, TEXT("ScanFrequency"),  scanFrequency);
    scanDay         = getInt(SEC_SCHEDULE, TEXT("ScanDay"),        scanDay);
    scanPath        = getStr(SEC_SCHEDULE, TEXT("ScanPath"),        scanPath);
    scanDescription = getStr(SEC_SCHEDULE, TEXT("ScanDescription"), scanDescription);
    scanMemory      = getInt(SEC_SCHEDULE, TEXT("ScanMemory"),      scanMemory) != 0;
    scanRunMissed   = getInt(SEC_SCHEDULE, TEXT("RunMissed"),       scanRunMissed) != 0;
    scanLastRunTime = getInt64(SEC_SCHEDULE, TEXT("ScanLastRun"),   scanLastRunTime);
    updateScheduled = getInt(SEC_SCHEDULE, TEXT("UpdateEnabled"),  updateScheduled) != 0;
    updateHour      = getInt(SEC_SCHEDULE, TEXT("UpdateHour"),     updateHour);
    updateMinute    = getInt(SEC_SCHEDULE, TEXT("UpdateMinute"),   updateMinute);
    updateFrequency = getInt(SEC_SCHEDULE, TEXT("UpdateFrequency"),updateFrequency);
    updateRunMissed = getInt(SEC_SCHEDULE, TEXT("UpdateRunMissed"),updateRunMissed) != 0;
    updateLastRunTime = getInt64(SEC_SCHEDULE, TEXT("UpdateLastRun"),updateLastRunTime);
    schedulerDebug  = getInt(SEC_SCHEDULE, TEXT("SchedulerDebug"), schedulerDebug) != 0;

    closeOnExit     = getInt(SEC_UI, TEXT("CloseOnExit"), closeOnExit)  != 0;
    trayNotify      = getInt(SEC_UI, TEXT("TrayNotify"),  trayNotify)   != 0;

    /* Preserve backward compatibility with INI files that contain empty log path values. */
    if (scanLogFile.empty())
    {
        TCHAR exedir[MAX_PATH];
        GetModuleFileName(NULL, exedir, MAX_PATH);
        TCHAR* slash = _tcsrchr(exedir, TEXT('\\'));
        if (slash)
            *(slash + 1) = '\0';
        scanLogFile = CW_ToNarrow(exedir) + "ClamScan.log";
    }
    if (updateLogFile.empty())
    {
        TCHAR exedir[MAX_PATH];
        GetModuleFileName(NULL, exedir, MAX_PATH);
        TCHAR* slash = _tcsrchr(exedir, TEXT('\\'));
        if (slash)
            *(slash + 1) = '\0';
        updateLogFile = CW_ToNarrow(exedir) + "FreshClam.log";
    }

    /* Migrate legacy install-dir defaults to user profile paths.
     * This avoids update failures when ClamWin is installed under Program Files. */
    {
        TCHAR exedir[MAX_PATH];
        GetModuleFileName(NULL, exedir, MAX_PATH);
        TCHAR* slash = _tcsrchr(exedir, TEXT('\\'));
        if (slash)
            *(slash + 1) = '\0';

        std::string exedirStr = CW_ToNarrow(exedir);
        std::string installDb         = exedirStr + "db";
        std::string installQuarantine = exedirStr + "Quarantine";
        std::string installScanLog    = exedirStr + "ClamScan.log";
        std::string installUpdateLog  = exedirStr + "FreshClam.log";

        TCHAR profile[MAX_PATH];
        DWORD profileLen = GetEnvironmentVariable(TEXT("USERPROFILE"), profile, MAX_PATH);
        if (profileLen > 0 && profileLen < MAX_PATH)
        {
            std::string profileRoot = CW_ToNarrow(profile) + "\\.clamwin";
            if (databasePath == installDb)
                databasePath = profileRoot + "\\db";
            if (quarantinePath == installQuarantine)
                quarantinePath = profileRoot + "\\Quarantine";
            if (scanLogFile == installScanLog)
                scanLogFile = profileRoot + "\\ClamScan.log";
            if (updateLogFile == installUpdateLog)
                updateLogFile = profileRoot + "\\FreshClam.log";
        }
    }

    includePatterns = getStr(SEC_CLAMAV, TEXT("IncludePatterns"), includePatterns);
    excludePatterns = getStr(SEC_CLAMAV, TEXT("ExcludePatterns"), excludePatterns);
    includePatterns = normalizeFilterPatterns(includePatterns);
    excludePatterns = normalizeFilterPatterns(excludePatterns);

    writeFreshclamConf();

    return true;
}

/* ─── Save ──────────────────────────────────────────────────── */

bool CWConfig::save() const
{
    /* Create directory if needed */
    std::string dir = iniPath;
    size_t slash = dir.rfind('\\');
    if (slash != std::string::npos)
    {
        dir.resize(slash);
        std::basic_string<TCHAR> tDir = CW_ToT(dir);
        CreateDirectory(tDir.c_str(), NULL);
    }

    setStr(SEC_CLAMAV, TEXT("Database"),       databasePath);
    setInt(SEC_CLAMAV, TEXT("ScanRecursive"),  scanRecursive  ? 1 : 0);
    setInt(SEC_CLAMAV, TEXT("ScanArchives"),   scanArchives   ? 1 : 0);
    setInt(SEC_CLAMAV, TEXT("ScanOle2"),       scanOle2       ? 1 : 0);
    setInt(SEC_CLAMAV, TEXT("ScanMail"),       scanMail       ? 1 : 0);
    setInt(SEC_CLAMAV, TEXT("InfectedAction"), infectedAction);
    setInt(SEC_CLAMAV, TEXT("InfectedOnly"),   infectedOnly   ? 1 : 0);
    setInt(SEC_CLAMAV, TEXT("MaxScanSize"),    maxScanSizeMb);
    setInt(SEC_CLAMAV, TEXT("MaxFileSize"),    maxFileSizeMb);
    setInt(SEC_CLAMAV, TEXT("MaxFiles"),       maxFiles);
    setInt(SEC_CLAMAV, TEXT("MaxRecursion"),   maxDepth);
    setStr(SEC_CLAMAV, TEXT("Quarantine"),     quarantinePath);
    setStr(SEC_CLAMAV, TEXT("LogFile"),        scanLogFile);
    setStr(SEC_CLAMAV, TEXT("Priority"),       priority);

    setStr(SEC_UPDATES, TEXT("DBMirror"),         dbMirror);
    setStr(SEC_UPDATES, TEXT("UpdateLog"),        updateLogFile);
    setInt(SEC_UPDATES, TEXT("UpdateOnStartup"),  updateOnStartup ? 1 : 0);
    setInt(SEC_UPDATES, TEXT("CheckVersion"),     checkVersion    ? 1 : 0);

    setInt(SEC_PROXY, TEXT("Enabled"),  proxyEnabled ? 1 : 0);
    setStr(SEC_PROXY, TEXT("Host"),     proxyHost);
    setInt(SEC_PROXY, TEXT("Port"),     proxyPort);
    setStr(SEC_PROXY, TEXT("User"),     proxyUser);
    setStr(SEC_PROXY, TEXT("Password"), proxyPass);

    setInt(SEC_ALERTS, TEXT("Enabled"), emailEnabled ? 1 : 0);
    setStr(SEC_ALERTS, TEXT("From"),    emailFrom);
    setStr(SEC_ALERTS, TEXT("To"),      emailTo);
    setStr(SEC_ALERTS, TEXT("SMTP"),    emailSmtp);

    setInt(SEC_SCHEDULE, TEXT("ScanEnabled"),    scanScheduled   ? 1 : 0);
    setInt(SEC_SCHEDULE, TEXT("ScanHour"),       scanHour);
    setInt(SEC_SCHEDULE, TEXT("ScanMinute"),     scanMinute);
    setInt(SEC_SCHEDULE, TEXT("ScanFrequency"),  scanFrequency);
    setInt(SEC_SCHEDULE, TEXT("ScanDay"),        scanDay);
    setStr(SEC_SCHEDULE, TEXT("ScanPath"),        scanPath);
    setStr(SEC_SCHEDULE, TEXT("ScanDescription"), scanDescription);
    setInt(SEC_SCHEDULE, TEXT("ScanMemory"),      scanMemory ? 1 : 0);
    setInt(SEC_SCHEDULE, TEXT("RunMissed"),       scanRunMissed ? 1 : 0);
    setInt64(SEC_SCHEDULE, TEXT("ScanLastRun"),   scanLastRunTime);
    setInt(SEC_SCHEDULE, TEXT("UpdateEnabled"),  updateScheduled ? 1 : 0);
    setInt(SEC_SCHEDULE, TEXT("UpdateHour"),     updateHour);
    setInt(SEC_SCHEDULE, TEXT("UpdateMinute"),   updateMinute);
    setInt(SEC_SCHEDULE, TEXT("UpdateFrequency"),updateFrequency);
    setInt(SEC_SCHEDULE, TEXT("UpdateRunMissed"),updateRunMissed ? 1 : 0);
    setInt64(SEC_SCHEDULE, TEXT("UpdateLastRun"),updateLastRunTime);
    setInt(SEC_SCHEDULE, TEXT("SchedulerDebug"), schedulerDebug ? 1 : 0);

    setInt(SEC_UI, TEXT("CloseOnExit"), closeOnExit ? 1 : 0);
    setInt(SEC_UI, TEXT("TrayNotify"),  trayNotify  ? 1 : 0);
    setStr(SEC_CLAMAV, TEXT("IncludePatterns"), includePatterns);
    setStr(SEC_CLAMAV, TEXT("ExcludePatterns"), excludePatterns);

    writeFreshclamConf();

    return true;
}

/* ─── Private helpers ────────────────────────────────────────── */

std::string CWConfig::getStr(LPCTSTR sec, LPCTSTR key,
                              const std::string& def) const
{
    TCHAR buf[1024];
    std::basic_string<TCHAR> tDef = CW_ToT(def);
    std::basic_string<TCHAR> tIniPath = CW_ToT(iniPath);
    GetPrivateProfileString(sec, key, tDef.c_str(),
                              buf, _countof(buf), tIniPath.c_str());
    return CW_ToNarrow(buf);
}

int CWConfig::getInt(LPCTSTR sec, LPCTSTR key, int def) const
{
    std::basic_string<TCHAR> tIniPath = CW_ToT(iniPath);
    return GetPrivateProfileInt(sec, key, def, tIniPath.c_str());
}

void CWConfig::setStr(LPCTSTR sec, LPCTSTR key,
                       const std::string& val) const
{
    std::basic_string<TCHAR> tVal = CW_ToT(val);
    std::basic_string<TCHAR> tIniPath = CW_ToT(iniPath);
    WritePrivateProfileString(sec, key, tVal.c_str(), tIniPath.c_str());
}

void CWConfig::setInt(LPCTSTR sec, LPCTSTR key, int val) const
{
    TCHAR buf[32];
    wsprintf(buf, TEXT("%d"), val);
    std::basic_string<TCHAR> tIniPath = CW_ToT(iniPath);
    WritePrivateProfileString(sec, key, buf, tIniPath.c_str());
}

long long CWConfig::getInt64(LPCTSTR sec, LPCTSTR key, long long def) const
{
    std::string valStr = getStr(sec, key, "");
    if (valStr.empty()) return def;
    return _atoi64(valStr.c_str());
}

void CWConfig::setInt64(LPCTSTR sec, LPCTSTR key, long long val) const
{
    TCHAR buf[64];
    _sntprintf(buf, _countof(buf), TEXT("%I64d"), val);
    buf[_countof(buf) - 1] = TEXT('\0');
    std::basic_string<TCHAR> tIniPath = CW_ToT(iniPath);
    WritePrivateProfileString(sec, key, buf, tIniPath.c_str());
}
