; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName={cm:ClamWinFreeAntivirus1}
AppVerName={cm:ClamWinFreeAntivirus1} 0.88.6
OutputBaseFilename=ClamWinL10N-26
AppPublisher=budtse
AppPublisherURL=http://www.clamwin.com/
AppSupportURL=http://www.clamwin.com/
AppUpdatesURL=http://www.clamwin.com/
DefaultDirName={code:BaseDir}\ClamWin
DefaultGroupName={cm:ClamWinFreeAntivirus2}
LicenseFile=SetupFiles\License.rtf
AllowNoIcons=true
MinVersion=4.1.1998,5.0.2195

ShowLanguageDialog=yes
LanguageDetectionMethod=locale
OutputDir=Output
OutputManifestFile=ClamwinL10N-Manifest.txt
Compression=lzma/ultra
InternalCompressLevel=max

SolidCompression=false
WizardImageFile=Setupfiles\WizModernImage.bmp
WizardSmallImageFile=Setupfiles\WizModernSmallImage.bmp
[Languages]
Name: en; MessagesFile: compiler:Default.isl
Name: ru; MessagesFile: compiler:Languages\Russian.isl
Name: nl; MessagesFile: compiler:Languages\Dutch.isl
Name: fr; MessagesFile: compiler:Languages\French.isl
Name: de; MessagesFile: compiler:Languages\German.isl
Name: it; MessagesFile: compiler:Languages\Italian.isl
Name: es; MessagesFile: compiler:Languages\Spanish.isl
;Name: cs; MessagesFile: compiler:Languages\Czech.isl

[Files]
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
;Source: cygwin\cygwin1.dll; DestDir: {app}\bin; Components: Cygwin; Flags: restartreplace uninsrestartdelete replacesameversion
;Source: cygwin\cygbz2-1.dll; DestDir: {app}\bin; Components: Cygwin; Flags: restartreplace uninsrestartdelete replacesameversion
;Source: cygwin\cyggmp-3.dll; DestDir: {app}\bin; Components: Cygwin; Flags: restartreplace uninsrestartdelete replacesameversion
;Source: cygwin\cygminires.dll; DestDir: {app}\bin; Components: Cygwin; Flags: restartreplace uninsrestartdelete replacesameversion
;Source: cygwin\cygz.dll; DestDir: {app}\bin; Components: Cygwin; Flags: restartreplace uninsrestartdelete replacesameversion
;Source: cygwin\cygcrypto-0.9.7.dll; DestDir: {app}\bin; Components: Cygwin; Flags: restartreplace uninsrestartdelete replacesameversion replacesameversion
;Source: cygwin\cygssl-0.9.7.dll; DestDir: {app}\bin; Components: Cygwin; Flags: restartreplace uninsrestartdelete replacesameversion replacesameversion
;Source: cygwin\cygcurl-2.dll; DestDir: {app}\bin; Components: Cygwin; Flags: restartreplace uninsrestartdelete replacesameversion replacesameversion
Source: py2exe\dist\bin\python23.dll; DestDir: {app}\bin; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\bin\ClamTray.exe; DestDir: {app}\bin; Components: ClamWin; Flags: restartreplace uninsrestartdelete replacesameversion
Source: py2exe\dist\bin\ClamWin.exe; DestDir: {app}\bin; Components: ClamWin; Flags: restartreplace uninsrestartdelete replacesameversion
Source: ..\doc\nl_BE\Manual_NL.chm; DestDir: {app}\doc; Components: InternationalHelp\Dutch; Flags: ignoreversion
Source: ..\doc\nl_BE\Manual_NL.pdf; DestDir: {app}\doc; Components: InternationalHelp\Dutch; Flags: ignoreversion
;Source: ..\doc\l10n\ItalianManual.chm; DestDir: {app}\doc; Components: InternationalHelp\Italian; Flags: replacesameversion
Source: ..\doc\en_UK\manual_EN.pdf; DestDir: {app}\doc; Components: ClamWin; Flags: ignoreversion
Source: ..\doc\en_UK\manual_en.chm; DestDir: {app}\doc; Components: ClamWin; Flags: ignoreversion; DestName: manual.chm
Source: ..\doc\ru_RU\manual_ru.chm; DestDir: {app}\doc; Components: InternationalHelp\Russian; Flags: ignoreversion
Source: ..\doc\fr_FR\manual_fr.pdf; DestDir: {app}\doc; Components: InternationalHelp\French; Flags: ignoreversion
Source: py2exe\dist\bin\img\Clam.png; DestDir: {app}\bin\img; Components: ClamWin; Flags: ignoreversion
Source: py2exe\dist\bin\img\ClamAV.png; DestDir: {app}\bin\img; Components: ClamWin; Flags: ignoreversion
Source: py2exe\dist\bin\img\netfarm.png; DestDir: {app}\bin\img; Components: ClamWin; Flags: ignoreversion
Source: py2exe\dist\bin\img\Control.png; DestDir: {app}\bin\img; Components: ClamWin; Flags: ignoreversion
Source: py2exe\dist\bin\img\Scan.png; DestDir: {app}\bin\img; Components: ClamWin; Flags: ignoreversion
Source: py2exe\dist\bin\img\ScanMem.png; DestDir: {app}\bin\img; Components: ClamWin; Flags: ignoreversion
Source: py2exe\dist\bin\img\FrameIcon.ico; DestDir: {app}\bin\img; Components: ClamWin; Flags: ignoreversion
Source: py2exe\dist\bin\img\TrayIcon.ico; DestDir: {app}\bin\img; Components: ClamWin; Flags: ignoreversion
Source: py2exe\dist\bin\img\Title.png; DestDir: {app}\bin\img; Components: ClamWin; Flags: ignoreversion
Source: py2exe\dist\bin\img\FD-logo.png; DestDir: {app}\bin\img; Components: ClamWin; Flags: ignoreversion
Source: py2exe\dist\bin\img\PythonPowered.gif; DestDir: {app}\bin\img; Components: ClamWin; Flags: ignoreversion
Source: py2exe\dist\bin\img\World.png; DestDir: {app}\bin\img; Components: ClamWin; Flags: ignoreversion
Source: py2exe\dist\bin\img\Support.png; DestDir: {app}\bin\img; Components: ClamWin; Flags: ignoreversion
Source: py2exe\dist\bin\img\ListScan.png; DestDir: {app}\bin\img; Components: ClamWin; Flags: ignoreversion
Source: py2exe\dist\bin\img\Splash.bmp; DestDir: {app}\bin\img; Components: ClamWin; Flags: ignoreversion
Source: ..\..\..\clamav-release\contrib\msvc\Release\clamscan.exe; DestDir: {app}\bin; Components: ClamAV; Flags: restartreplace uninsrestartdelete replacesameversion
Source: ..\..\..\clamav-release\contrib\msvc\Release\freshclam.exe; DestDir: {app}\bin; Components: ClamAV; Flags: restartreplace uninsrestartdelete replacesameversion
Source: ..\..\..\clamav-release\contrib\msvc\Release\sigtool.exe; DestDir: {app}\bin; Components: ClamAV; Flags: restartreplace uninsrestartdelete replacesameversion
Source: ..\..\..\clamav-release\contrib\msvc\Release\libclamav.dll; DestDir: {app}\bin; Components: ClamAV; Flags: restartreplace uninsrestartdelete replacesameversion

; Copy the Gettext locale files

;Source: ..\locale\ca_ES.mo; DestDir: {app}\locale\ca_ES\LC_MESSAGES; DestName: clamwin.mo; Components: ClamWin; Flags: restartreplace uninsrestartdelete replacesameversion
;Source: ..\locale\cs_CZ.mo; DestDir: {app}\locale\cs_CZ\LC_MESSAGES; DestName: clamwin.mo; Components: ClamWin; Flags: restartreplace uninsrestartdelete replacesameversion
Source: ..\locale\de_DE.mo; DestDir: {app}\locale\de_DE\LC_MESSAGES; DestName: clamwin.mo; Components: ClamWin; Flags: restartreplace uninsrestartdelete replacesameversion
Source: ..\locale\es_ES.mo; DestDir: {app}\locale\es_ES\LC_MESSAGES; DestName: clamwin.mo; Components: ClamWin; Flags: restartreplace uninsrestartdelete replacesameversion
Source: ..\locale\fr_FR.mo; DestDir: {app}\locale\fr_FR\LC_MESSAGES; DestName: clamwin.mo; Components: ClamWin; Flags: restartreplace uninsrestartdelete replacesameversion
Source: ..\locale\it_IT.mo; DestDir: {app}\locale\it_IT\LC_MESSAGES; DestName: clamwin.mo; Components: ClamWin; Flags: restartreplace uninsrestartdelete replacesameversion
;Source: ..\locale\ko_KR.mo; DestDir: {app}\locale\ko_KR\LC_MESSAGES; DestName: clamwin.mo; Components: ClamWin; Flags: restartreplace uninsrestartdelete replacesameversion
Source: ..\locale\nl_BE.mo; DestDir: {app}\locale\nl_BE\LC_MESSAGES; DestName: clamwin.mo; Components: ClamWin; Flags: restartreplace uninsrestartdelete replacesameversion
Source: ..\locale\ru_RU.mo; DestDir: {app}\locale\ru_RU\LC_MESSAGES; DestName: clamwin.mo; Components: ClamWin; Flags: restartreplace uninsrestartdelete replacesameversion
;Source: ..\locale\pt_PT.mo; DestDir: {app}\locale\pt_PT\LC_MESSAGES; DestName: clamwin.mo; Components: ClamWin; Flags: restartreplace uninsrestartdelete replacesameversion
;Source: ..\locale\sv_SE.mo; DestDir: {app}\locale\sv_SE\LC_MESSAGES; DestName: clamwin.mo; Components: ClamWin; Flags: restartreplace uninsrestartdelete replacesameversion
;Source: ..\locale\tr_TR.mo; DestDir: {app}\locale\tr_TR\LC_MESSAGES; DestName: clamwin.mo; Components: ClamWin; Flags: restartreplace uninsrestartdelete replacesameversion
;Source: ..\locale\zh_CN.mo; DestDir: {app}\locale\zh_CN\LC_MESSAGES; DestName: clamwin.mo; Components: ClamWin; Flags: restartreplace uninsrestartdelete replacesameversion


; on xp and greater VC80 CRT needs to be installed in Microsoft.VC80.CRT
Source: Microsoft.VC80.CRT\Microsoft.VC80.CRT.manifest; DestDir: {app}\bin\Microsoft.VC80.CRT; Components: ClamAV; Check: IsXPOrLater
Source: Microsoft.VC80.CRT\msvcm80.dll; DestDir: {app}\bin\Microsoft.VC80.CRT; Components: ClamAV; Flags: restartreplace uninsrestartdelete; Check: IsXPOrLater
Source: Microsoft.VC80.CRT\msvcr80.dll; DestDir: {app}\bin\Microsoft.VC80.CRT; Components: ClamAV; Flags: restartreplace uninsrestartdelete; Check: IsXPOrLater
Source: Microsoft.VC80.CRT\msvcp80.dll; DestDir: {app}\bin\Microsoft.VC80.CRT; Components: ClamAV; Flags: restartreplace uninsrestartdelete; Check: IsXPOrLater
; on 2000 and 98 VC80 CRT needs to be installed in the same dir; no manifest
Source: Microsoft.VC80.CRT\msvcm80.dll; DestDir: {app}\bin; Components: ClamAV; Flags: restartreplace uninsrestartdelete; Check: not IsXPOrLater
Source: Microsoft.VC80.CRT\msvcr80.dll; DestDir: {app}\bin; Components: ClamAV; Flags: restartreplace uninsrestartdelete; Check: not IsXPOrLater
Source: Microsoft.VC80.CRT\msvcp80.dll; DestDir: {app}\bin; Components: ClamAV; Flags: restartreplace uninsrestartdelete; Check: not IsXPOrLater


;Source: ..\clamav-stable\sigtool\sigtool.exe; DestDir: {app}\bin; Components: ClamAV; Flags: restartreplace uninsrestartdelete replacesameversion
; TODO : Copy Unicode build in NT and ANSI in 9x
Source: ..\cpp\Release\ExpShell.dll; DestDir: {app}\bin; Components: ExplorerShell; Flags: restartreplace uninsrestartdelete; Check: IsWin9x
Source: ..\cpp\Release_Unicode\ExpShell.dll; DestDir: {app}\bin; Components: ExplorerShell; Flags: restartreplace uninsrestartdelete; Check: UsingWinNT
;Source: ..\cpp\Release_x64\ExpShell64.dll; DestDir: {app}\bin; Components: ExplorerShell; Flags: restartreplace uninsrestartdelete 64bit; Check: IsWin64

Source: py2exe\dist\bin\WClose.exe; DestDir: {app}\bin; Components: ClamWin; Flags: restartreplace uninsrestartdelete replacesameversion
Source: py2exe\dist\bin\w9xpopen.exe; DestDir: {app}\bin; Components: ClamWin; Flags: restartreplace uninsrestartdelete replacesameversion
Source: py2exe\dist\bin\OlAddin.exe; DestDir: {app}\bin; Components: OutlookAddin; Flags: restartreplace uninsrestartdelete replacesameversion
;Source: {%TEMP|{localappdata}}\clamwin-src.zip; DestDir: {app}\src; Components: Sources; Flags: external ignoreversion
;Source: {%TEMP|{localappdata}}\clamav-src.tar.gz; DestDir: {app}\src; Components: Sources; Flags: external ignoreversion
;Source: {%TEMP|{localappdata}}\cygwin-src.tar.bz2; DestDir: {app}\src; Components: Sources; Flags: external replacesameversion

Source: py2exe\dist\lib\_socket.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\_sre.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\_ssl.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\_bsddb.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\_winreg.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\clamwin.zip; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\datetime.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\mxDateTime.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
;Source: py2exe\dist\lib\exchange.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
;Source: py2exe\dist\lib\exchdapi.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\shell.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\htmlc.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\gizmosc.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\mapi.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\pythoncom23.dll; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\pywintypes23.dll; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\unicodedata.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\bin\w9xpopen.exe; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\win32api.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\win32clipboard.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\win32event.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\win32file.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\win32gui.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\win32pipe.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\win32process.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\win32trace.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\win32security.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\wxc.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\wxmsw24h.dll; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
Source: py2exe\dist\lib\zlib.pyd; DestDir: {app}\lib; Components: ClamWin; Flags: restartreplace uninsrestartdelete
;Source: py2exe\dist\lib\BalloonTip.pyd; DestDir: {app}\lib; Components: ClamWin; Check: IsWin9x; Flags: restartreplace uninsrestartdelete
[Icons]
Name: {group}\Virus Scanner; Filename: {app}\bin\ClamWin.exe; WorkingDir: {app}\bin; Comment: {cm:ClamWinFreeAntivirus2}; Components: ClamWin
Name: {code:DesktopDir}\ClamWin Antivirus; Filename: {app}\bin\ClamWin.exe; WorkingDir: {app}\bin; Comment: {cm:ClamWinFreeAntivirus2}; Components: ClamWin; Tasks: desktopicon
Name: {group}\Help\Printable Manual; Filename: {app}\bin\manual.pdf; Components: ; WorkingDir: {app}\bin
Name: {group}\Help\Online Help; Filename: {app}\bin\manual.chm; WorkingDir: {app}\bin; Comment: {cm:ClamWinFreeAntivirus2}; Components: ClamWin
Name: {group}\Help\International\Russian Help; Filename: {app}\bin\manual_ru.chm; WorkingDir: {app}\bin; Comment: {cm:ClamWinFreeAntivirus2}; Components: InternationalHelp\Russian
Name: {group}\Help\International\French Help; Filename: {app}\bin\manual_fr.pdf; WorkingDir: {app}\bin; Comment: {cm:ClamWinFreeAntivirus2}; Components: InternationalHelp\French
Name: {group}\Help\International\Dutch Help; Filename: {app}\bin\Manual_NL.chm; WorkingDir: {app}\bin; Comment: {cm:ClamWinFreeAntivirus2}; Components: InternationalHelp\Dutch
;Name: {group}\Help\International\Italian Help; Filename: {app}\bin\ItalianManual.chm; WorkingDir: {app}\bin; Comment: ClamWin Antivirus; Components: InternationalHelp\Italian

[Run]
; NOTE: The following entry contains an English phrase ("Launch"). You are free to translate it into another language if required.
Filename: {app}\bin\ClamWin.exe; Parameters: --mode=update --close; WorkingDir: {app}\bin; StatusMsg: {cm:DownloadDB2}; Components: ClamWin; Tasks: DownloadDB
Filename: {app}\bin\ClamTray.exe; WorkingDir: {app}\bin; Flags: nowait; Components: ClamWin
[Dirs]
; create clamwin folders in common profiles dir if all users is selected and set permissions so that other users can modify
Name: {code:CommonProfileDir}\.clamwin\db; Components: ClamAV; Permissions: authusers-full; Check: IsAllUsers
Name: {code:CommonProfileDir}\.clamwin\log; Components: ClamAV; Permissions: authusers-full; Check: IsAllUsers
Name: {code:CommonProfileDir}\.clamwin\quarantine; Components: ClamAV; Permissions: authusers-full; Check: IsAllUsers
;for non-admin user create tese folders in user's profile dir, don't modify security
Name: {code:CommonProfileDir}\.clamwin\db; Components: ClamAV; Check: not IsAllUsers
Name: {code:CommonProfileDir}\.clamwin\log; Components: ClamAV; Check: not IsAllUsers
Name: {code:CommonProfileDir}\.clamwin\quarantine; Components: ClamAV; Check: not IsAllUsers
Name: {app}\bin; Components: ExplorerShell ClamWin
Name: {app}\lib; Components: ClamWin
Name: {app}\bin\img; Components: ClamWin
Name: {app}\locale; Components: ClamWin
[_ISTool]

[Components]
Name: ClamAV; Description: {cm:ClamAVFiles1}; Flags: fixed; Types: full custom typical
Name: ClamWin; Description: {cm:ClamWinFiles1}; Flags: fixed; Types: full custom typical
Name: ExplorerShell; Description: {cm:IntegrationExplorer1}; Types: full custom typical
Name: OutlookAddin; Description: {cm:IntegrationOutlook1}; Types: full custom typical; Check: IsOutlookInstalled
Name: InternationalHelp; Description: {cm:InternationalHelpFiles1}; Types: full
Name: InternationalHelp\Russian; Description: {cm:RussianHelpFiles1}; Types: full
Name: InternationalHelp\French; Description: {cm:FrenchHelpFiles1}; Types: full
Name: InternationalHelp\Dutch; Description: {cm:DutchHelpFiles1}; Types: full
;Name: InternationalHelp\Italian; Description: Italian Help Files; Types: full
;Name: Sources; Description: {cm:DownloadSourceCode1}; ExtraDiskSpaceRequired: 9437184; Types: full
[INI]
Filename: {app}\bin\ClamWin.conf; Section: ClamAV; Key: clamscan; String: {app}\bin\clamscan.exe; Check: IsIniValueEmpty(ExpandConstant('ClamAV*clamscan*{app}\bin\ClamWin.conf'))
Filename: {app}\bin\ClamWin.conf; Section: ClamAV; Key: freshclam; String: {app}\bin\freshclam.exe; Check: IsIniValueEmpty(ExpandConstant('ClamAV*freshclam*{app}\bin\ClamWin.conf'))
Filename: {app}\bin\ClamWin.conf; Section: ClamAV; Key: database; String: {code:CommonProfileDir}\.clamwin\db; Check: IsIniValueEmpty(ExpandConstant('ClamAV*database*{app}\bin\ClamWin.conf'))
Filename: {app}\bin\ClamWin.conf; Section: ClamAV; Key: quarantinedir; String: {code:CommonProfileDir}\.clamwin\quarantine; Check: IsIniValueEmpty(ExpandConstant('ClamAV*quarantinedir*{app}\bin\ClamWin.conf'))
Filename: {app}\bin\ClamWin.conf; Section: ClamAV; Key: logfile; String: {code:CommonProfileDir}\.clamwin\log\ClamScanLog.txt; Check: IsIniValueEmpty(ExpandConstant('ClamAV*logfile*{app}\bin\ClamWin.conf'))
Filename: {app}\bin\ClamWin.conf; Section: Updates; Key: dbupdatelogfile; String: {code:CommonProfileDir}\.clamwin\log\ClamUpdateLog.txt; Check: IsIniValueEmpty(ExpandConstant('Updates*dbupdatelogfile*{app}\bin\ClamWin.conf'))
Filename: {app}\bin\ClamWin.conf; Section: Updates; Key: time; String: {code:CurTime}; Check: IsIniValueEmpty(ExpandConstant('Updates*time*{app}\bin\ClamWin.conf'))

;[_ISToolDownload]
;Name: Sources_ClamWin; Description: {cm:ClamWinSourceCode1}; GroupDescription: Source Code; Flags: unchecked; Source: http://osdn.dl.sourceforge.net/sourceforge/clamwin/clamwin-0.88.2.3-src.zip; DestDir: {%TEMP|{localappdata}}; DestName: clamwin-src.zip; Components: Sources
;Name: Sources_ClamAV; Description: {cm:ClamAVSourceCode1}; GroupDescription: Source Code; Flags: unchecked; Source: http://osdn.dl.sourceforge.net/sourceforge/clamav/clamav-0.88.2.tar.gz; DestDir: {%TEMP|{localappdata}}; DestName: clamav-src.tar.gz; Components: Sources
;Name: Sources_Cygwin; Description: Cygwin Source Code; GroupDescription: Source Codes; Flags: unchecked; Source: http://mirrors.kernel.org/sources.redhat.com/cygwin/release/cygwin/cygwin-1.5.18-1-src.tar.bz2; DestDir: {%TEMP|{localappdata}}; DestName: cygwin-src.tar.bz2; Components: Sources

[Types]
Name: typical; Description: {cm:TypicalInstallation1}
Name: custom; Description: {cm:CustomInstallation1}; Flags: iscustom
Name: full; Description: {cm:FullInstallation1}

[UninstallDelete]
Name: {tmp}\ClamWin_Scheduler_Info; Type: files; Components: ClamWin
Name: {tmp}\ClamWin_Upadte_Time; Type: files; Components: ClamWin
Name: {app}\bin\ClamWin.conf; Type: files
Name: {userappdata}\.clamwin; Type: filesandordirs
Name: {code:CommonProfileDir}\.clamwin; Type: filesandordirs

[Registry]
; write to HKLM and HKCR when user is admin
; and to HKCU when not

; ClamWin entries
Root: HKLM; Subkey: Software\Microsoft\Windows\CurrentVersion\Run; ValueType: string; ValueName: ClamWin; ValueData: """{app}\bin\ClamTray.exe"" --logon"; Flags: uninsdeletevalue; Components: ClamWin; Check: IsAllUsers
Root: HKLM; Subkey: Software\ClamWin; ValueType: string; ValueName: Path; ValueData: {app}\bin; Flags: uninsdeletekey deletevalue; Components: ClamWin; Check: IsAllUsers
Root: HKLM64; Subkey: Software\ClamWin; ValueType: string; ValueName: Path; ValueData: {app}\bin; Flags: uninsdeletekey deletevalue; Components: ClamWin; Check: IsAllUsers and IsWin64
Root: HKLM; Subkey: Software\ClamWin; ValueType: dword; ValueName: Version; ValueData: 886; Flags: uninsdeletekey deletevalue; Components: ClamWin; Check: IsAllUsers
Root: HKCU; Subkey: Software\Microsoft\Windows\CurrentVersion\Run; ValueType: string; ValueName: ClamWin; ValueData: """{app}\bin\ClamTray.exe"" --logon"; Flags: uninsdeletevalue; Components: ClamWin; Check: not IsAllUsers
Root: HKCU; Subkey: Software\ClamWin; ValueType: string; ValueName: Path; ValueData: {app}\bin; Flags: uninsdeletekey deletevalue; Components: ClamWin; Check: not IsAllUsers
Root: HKCU64; Subkey: Software\ClamWin; ValueType: string; ValueName: Path; ValueData: {app}\bin; Flags: uninsdeletekey deletevalue; Components: ClamWin; Check: not IsAllUsers and IsWin64
Root: HKCU; Subkey: Software\ClamWin; ValueType: dword; ValueName: Version; ValueData: 886; Flags: uninsdeletekey deletevalue; Components: ClamWin; Check: not IsAllUsers

; ExplorerShell entries
Root: HKCR; Subkey: CLSID\{{65713842-C410-4f44-8383-BFE01A398C90}\InProcServer32; ValueType: string; ValueData: {app}\bin\ExpShell.dll; Flags: uninsdeletekey; Components: ExplorerShell; Check: IsAllUsers
Root: HKCR64; Subkey: CLSID\{{65713842-C410-4f44-8383-BFE01A398C90}\InProcServer32; ValueType: string; ValueData: {app}\bin\ExpShell64.dll; Flags: uninsdeletekey; Components: ExplorerShell; Check: IsAllUsers and IsWin64
Root: HKCR; Subkey: CLSID\{{65713842-C410-4f44-8383-BFE01A398C90}\InProcServer32; ValueType: string; ValueData: Apartment; Flags: uninsdeletekey; ValueName: ThreadingModel; Components: ExplorerShell; Check: IsAllUsers
Root: HKCR64; Subkey: CLSID\{{65713842-C410-4f44-8383-BFE01A398C90}\InProcServer32; ValueType: string; ValueData: Apartment; Flags: uninsdeletekey; ValueName: ThreadingModel; Components: ExplorerShell; Check: IsAllUsers and IsWin64
Root: HKCR; Subkey: *\shellex\ContextMenuHandlers\ClamWin; ValueType: string; ValueData: {{65713842-C410-4f44-8383-BFE01A398C90}; Flags: uninsdeletekey; Components: ExplorerShell; Check: IsAllUsers
Root: HKCR; Subkey: Folder\shellex\ContextMenuHandlers\ClamWin; ValueType: string; ValueData: {{65713842-C410-4f44-8383-BFE01A398C90}; Flags: uninsdeletekey; Components: ExplorerShell; Check: IsAllUsers


Root: HKCU; Subkey: Software\Classes\CLSID\{{65713842-C410-4f44-8383-BFE01A398C90}\InProcServer32; ValueType: string; ValueData: {app}\bin\ExpShell.dll; Flags: uninsdeletekey; Components: ExplorerShell; Check: not IsAllUsers
Root: HKCU64; Subkey: Software\Classes\CLSID\{{65713842-C410-4f44-8383-BFE01A398C90}\InProcServer32; ValueType: string; ValueData: {app}\bin\ExpShell64.dll; Flags: uninsdeletekey; Components: ExplorerShell; Check: not IsAllUsers and IsWin64
Root: HKCU; Subkey: Software\Classes\CLSID\{{65713842-C410-4f44-8383-BFE01A398C90}\InProcServer32; ValueType: string; ValueData: Apartment; Flags: uninsdeletekey; ValueName: ThreadingModel; Components: ExplorerShell; Check: not IsAllUsers
Root: HKCU64; Subkey: Software\Classes\CLSID\{{65713842-C410-4f44-8383-BFE01A398C90}\InProcServer32; ValueType: string; ValueData: Apartment; Flags: uninsdeletekey; ValueName: ThreadingModel; Components: ExplorerShell; Check: not IsAllUsers and IsWin64
Root: HKCU; Subkey: Software\Classes\*\shellex\ContextMenuHandlers\ClamWin; ValueType: string; ValueData: {{65713842-C410-4f44-8383-BFE01A398C90}; Flags: uninsdeletekey; Components: ExplorerShell; Check: not IsAllUsers
Root: HKCU; Subkey: Software\Classes\Folder\shellex\ContextMenuHandlers\ClamWin; ValueType: string; ValueData: {{65713842-C410-4f44-8383-BFE01A398C90}; Flags: uninsdeletekey; Components: ExplorerShell; Check: not IsAllUsers

; OutlookAddin entries for all users
;delete COM InprocServer32 key if present (we moved to EXE COM server)
Root: HKCR; Subkey: CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}\InprocServer32; Components: OutlookAddin; Check: IsAllUsers; Flags: deletekey noerror dontcreatekey
;install new EXE COM server
Root: HKCR; Subkey: AppID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}; ValueType: string; ValueData: ClamWin.OutlookAddin; Flags: uninsdeletekey; Components: OutlookAddin; Check: IsAllUsers
Root: HKCR; Subkey: CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}; ValueType: string; ValueData: ClamWin.OutlookAddin; Flags: uninsdeletekey; Components: OutlookAddin; Check: IsAllUsers
Root: HKCR; Subkey: CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}\LocalServer32; ValueType: string; ValueData: {app}\bin\OlAddin.exe /Automate; Flags: uninsdeletekey; Components: OutlookAddin; Check: IsAllUsers
Root: HKCR; Subkey: CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}\PythonCOM; ValueType: string; ValueData: OlAddin.OutlookAddin; Flags: uninsdeletekey; Components: OutlookAddin; Check: IsAllUsers
Root: HKCR; Subkey: CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}\PythonCOMPolicy; ValueType: string; ValueData: win32com.server.policy.EventHandlerPolicy; Flags: uninsdeletekey; Components: OutlookAddin; Check: IsAllUsers
Root: HKCR; Subkey: CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}\PythonCOMPath; ValueType: string; ValueData: {app}\bin; Flags: uninsdeletekey; Components: OutlookAddin; Check: IsAllUsers
Root: HKCR; Subkey: CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}\Implemented Categories\{{B3EF80D0-68E2-11D0-A689-00C04FD658FF}; Flags: uninsdeletekey; Components: OutlookAddin; Check: IsAllUsers
Root: HKCR; Subkey: CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}\Debugging; ValueType: string; ValueData: 0; Flags: uninsdeletekey; Components: OutlookAddin; Check: IsAllUsers
Root: HKCR; Subkey: CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}\ProgID; ValueType: string; ValueData: ClamWin.OutlookAddin; Flags: uninsdeletekey; Components: OutlookAddin; Check: IsAllUsers
Root: HKCR; Subkey: ClamWin.OutlookAddin; ValueType: string; ValueData: ClamWin.OutlookAddin; Flags: uninsdeletekey; Components: OutlookAddin; Check: IsAllUsers
Root: HKCR; Subkey: ClamWin.OutlookAddin\CLSID; ValueType: string; ValueData: {{E77FA584-1433-4af3-800D-AEC49BCCCB11}; Flags: uninsdeletekey; Components: OutlookAddin; Check: IsAllUsers

Root: HKLM; Subkey: Software\Microsoft\Office\Outlook\Addins\ClamWin.OutlookAddin; ValueType: dword; ValueName: CommandLineSafe; ValueData: 0; Flags: uninsdeletekey; Components: OutlookAddin; Check: IsAllUsers
Root: HKLM; Subkey: Software\Microsoft\Office\Outlook\Addins\ClamWin.OutlookAddin; ValueType: dword; ValueName: LoadBehavior; ValueData: 3; Flags: uninsdeletekey; Components: OutlookAddin; Check: IsAllUsers
Root: HKLM; Subkey: Software\Microsoft\Office\Outlook\Addins\ClamWin.OutlookAddin; ValueType: string; ValueName: Description; ValueData: ClamWin Antivirus; Flags: uninsdeletekey; Components: OutlookAddin; Check: IsAllUsers
Root: HKLM; Subkey: Software\Microsoft\Office\Outlook\Addins\ClamWin.OutlookAddin; ValueType: string; ValueName: FriendlyName; ValueData: ClamWin Antivirus; Flags: uninsdeletekey; Components: OutlookAddin; Check: IsAllUsers

; OutlookAddin entries for current user
;delete COM InprocServer32 key if present (we moved to EXE COM server)
Root: HKCU; Subkey: Software\Classes\CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}\InprocServer32; Components: OutlookAddin; Check: not IsAllUsers; Flags: deletekey dontcreatekey noerror
;install new COM EXE server
Root: HKCU; Subkey: Software\Classes\AppID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}; ValueType: string; ValueData: ClamWin.OutlookAddin; Flags: uninsdeletekey; Components: OutlookAddin; Check: not IsAllUsers
Root: HKCU; Subkey: Software\Classes\CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}; ValueType: string; ValueData: ClamWin.OutlookAddin; Flags: uninsdeletekey; Components: OutlookAddin; Check: not IsAllUsers
Root: HKCU; Subkey: Software\Classes\CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}\LocalServer32; ValueType: string; ValueData: {app}\bin\OlAddin.exe /Automate; Flags: uninsdeletekey; Components: OutlookAddin; Check: not IsAllUsers
Root: HKCU; Subkey: Software\Classes\CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}\PythonCOM; ValueType: string; ValueData: OlAddin.OutlookAddin; Flags: uninsdeletekey; Components: OutlookAddin; Check: not IsAllUsers
Root: HKCU; Subkey: Software\Classes\CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}\PythonCOMPolicy; ValueType: string; ValueData: win32com.server.policy.EventHandlerPolicy; Flags: uninsdeletekey; Components: OutlookAddin; Check: not IsAllUsers
Root: HKCU; Subkey: Software\Classes\CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}\PythonCOMPath; ValueType: string; ValueData: {app}\bin; Flags: uninsdeletekey; Components: OutlookAddin; Check: not IsAllUsers
Root: HKCU; Subkey: Software\Classes\CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}\Implemented Categories\{{B3EF80D0-68E2-11D0-A689-00C04FD658FF}; Flags: uninsdeletekey; Components: OutlookAddin; Check: not IsAllUsers
Root: HKCU; Subkey: Software\Classes\CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}\Debugging; ValueType: string; ValueData: 0; Flags: uninsdeletekey; Components: OutlookAddin; Check: not IsAllUsers
Root: HKCU; Subkey: Software\Classes\CLSID\{{E77FA584-1433-4af3-800D-AEC49BCCCB11}\ProgID; ValueType: string; ValueData: ClamWin.OutlookAddin; Flags: uninsdeletekey; Components: OutlookAddin; Check: not IsAllUsers
Root: HKCU; Subkey: Software\Classes\ClamWin.OutlookAddin; ValueType: string; ValueData: ClamWin.OutlookAddin; Flags: uninsdeletekey; Components: OutlookAddin; Check: not IsAllUsers
Root: HKCU; Subkey: Software\Classes\ClamWin.OutlookAddin\CLSID; ValueType: string; ValueData: {{E77FA584-1433-4af3-800D-AEC49BCCCB11}; Flags: uninsdeletekey; Components: OutlookAddin; Check: not IsAllUsers

Root: HKCU; Subkey: Software\Microsoft\Office\Outlook\Addins\ClamWin.OutlookAddin; ValueType: dword; ValueName: CommandLineSafe; ValueData: 0; Flags: uninsdeletekey; Components: OutlookAddin; Check: not IsAllUsers
Root: HKCU; Subkey: Software\Microsoft\Office\Outlook\Addins\ClamWin.OutlookAddin; ValueType: dword; ValueName: LoadBehavior; ValueData: 3; Flags: uninsdeletekey; Components: OutlookAddin; Check: not IsAllUsers
Root: HKCU; Subkey: Software\Microsoft\Office\Outlook\Addins\ClamWin.OutlookAddin; ValueType: string; ValueName: Description; ValueData: ClamWin Antivirus; Flags: uninsdeletekey; Components: OutlookAddin; Check: not IsAllUsers
Root: HKCU; Subkey: Software\Microsoft\Office\Outlook\Addins\ClamWin.OutlookAddin; ValueType: string; ValueName: FriendlyName; ValueData: ClamWin Antivirus; Flags: uninsdeletekey; Components: OutlookAddin; Check: not IsAllUsers

[Tasks]
Name: DownloadDB; Description: {cm:DownloadDB1}; GroupDescription: {cm:DownloadDB3}; Components: ClamAV
; NOTE: The following entry contains English phrases ("Create a desktop icon" and "Additional icons"). You are free to translate them into another language if required.
Name: desktopicon; Description: {cm:CreateDesktop1}; GroupDescription: {cm:CreateDesktop2}; Flags: unchecked
[UninstallRun]
Filename: {app}\bin\WClose.exe; WorkingDir: {app}\bin

[CustomMessages]
en.LanguageName=English
en.InitializeWizard1=Select Installation Options
en.InitializeWizard2=Who should this application be installed for?
en.InitializeWizard3=Please select whether you wish to make this software available to all users or just yourself.
en.InitializeWizard4=&Anyone who uses this computer (all users)
en.InitializeWizard5=Only for &me (
en.NoOutlookRunning1=You must close Outlook before ClamWin can be installed.
en.NoOutlookRunning2=Please close all Outlook Windows (using "File->Exit and Log off"
en.NoOutlookRunning3=if available) and click Retry, or click Cancel to exit the installation.
en.NoOutlookRunning4=If this message persists after closing all Outlook windows, you may
en.NoOutlookRunning5=need to log off from Windows, and try again.
en.NoOutlookRunning6=The Outlook mail delivery agent is still running.
en.NoOutlookRunning7=If you only recently closed Outlook, wait a few seconds and click Retry.
en.NoOutlookRunning8=If this message persists, you may need to log off from Windows, and try again.
en.CloseClamWin1=The Setup detected a previous version of the software is installed.
en.CloseClamWin2=Would you like to close the program now? (Recommended)
en.InitializeSetup1=Setup detected that a newer version of the software is already installed.
en.InitializeSetup2=Setup will terminate now.
en.DeInitializeSetup1=Please restart your computer in order to complete the installation of ClamWin Antivirus.
en.RemoveSetup1=The Setup detected a previous version of the software is already installed on this computer. Click Yes to uninstall it now.
en.DownloadDB1=Download Virus Database Files. (Do not Select if you connect via a Proxy Server)
en.DownloadDB2=Downloading Virus Database Files.
en.DownloadDB3=Download
en.CreateDesktop1=Create a &desktop icon
en.CreateDesktop2=Additional icons:
en.TypicalInstallation1=Typical Installation
en.CustomInstallation1=Custom Installation
en.FullInstallation1=Full Installation
en.ClamWinSourceCode1=ClamWin Source Code
en.ClamAVSourceCode1=ClamAV Source Code
en.InternationalHelpFiles1=International Help Files
en.RussianHelpFiles1=Russian Help Files
en.FrenchHelpFiles1=French Help Files
en.DutchHelpFiles1=Dutch Help Files
en.DownloadSourceCode1=Download Source Code
en.ClamAVFiles1=ClamAV Files
en.ClamWinFiles1=ClamWin Files
en.IntegrationExplorer1=Integration with Windows Explorer
en.IntegrationOutlook1=Integration with Microsoft Outlook
en.ClamWinFreeAntivirus1=ClamWin Free Antivirus
en.ClamWinFreeAntivirus2=ClamWin Antivirus

de.LanguageName=Deutsch
de.InitializeWizard1=Installations-Optionen festlegen
de.InitializeWizard2=Für wen soll dieses Programm installiert werden?
de.InitializeWizard3=Bitte wählen Sie, ob dieses Programm für alle Benutzer installiert werden soll, oder nur für Sie selbst.
de.InitializeWizard4=&Alle Benutzer
de.InitializeWizard5=Nur für &Mich (
de.NoOutlookRunning1=Sie müssen Outlook schließen, bevor Sie ClamWin installieren können!
de.NoOutlookRunning2=Bitte schließen Sie alle Outlook-Fenster (wenn möglich über "Datei->Beenden")
de.NoOutlookRunning3=und klicken Sie "Wiederholen". Ansonsten "Abbrechen", um das Installationsprogramm zu Verlassen.
de.NoOutlookRunning4=Falls diese Meldung nach dem Schließen von Outlook immernoch angezeigt wird,
de.NoOutlookRunning5=starten Sie Windows neu, und versuchen Sie es noch einmal.
de.NoOutlookRunning6=Die Outlook-Nachrichtenübermittlung ist noch aktiv.
de.NoOutlookRunning7=Wenn Sie Outlook eben erst geschlossen haben, warten Sie ein paar Sekunden und versuchen es dann erneut.
de.NoOutlookRunning8=Falls diese Meldung wiederholt angezeigt wird, starten Sie Windows erneut.
de.CloseClamWin1=Setup hat eine vorherige Installation von ClamWin gefunden.
de.CloseClamWin2=Laufendes ClamWin beenden? (Empfohlen)
de.InitializeSetup1=Es ist bereits eine neuere Version von ClamWin installiert.
de.InitializeSetup2=Setup wird abgebrochen.
de.DeInitializeSetup1=Bitte starten Sie den Computer neu, damit die Installation von ClamWin Antivirus abgeschlossen werden kann.
de.RemoveSetup1=Setup hat eine vorherige Installation von ClamWin gefunden. Klicken Sie auf Ja, um Diese jetzt zu deinstallieren.
de.DownloadDB1=Viren-Datenbank herunterladen (ohne Proxy-Server)
de.DownloadDB2=Lade Viren-Datenbank herunter...
de.DownloadDB3=Internet Update
de.CreateDesktop1=&Desktop-Verknüpfung erstellen
de.CreateDesktop2=Zusätzliche Symbole:
de.TypicalInstallation1=Typische Installation
de.CustomInstallation1=Benutzerdefinierte Installation
de.FullInstallation1=Vollständige Installation
de.ClamWinSourceCode1=ClamWin Source Code
de.ClamAVSourceCode1=ClamAV Source Code
de.InternationalHelpFiles1=Internationale Hilfe Dateien
de.RussianHelpFiles1=Russische Hilfe Dateien
de.FrenchHelpFiles1=Französische Hilfe Dateien
de.DutchHelpFiles1=Niederländische Hilfe Dateien
de.DownloadSourceCode1=Source Code herunterladen
de.ClamAVFiles1=ClamAV Dateien
de.ClamWinFiles1=ClamWin Dateien
de.IntegrationExplorer1=Integration in den Windows Explorer
de.IntegrationOutlook1=Integration in Microsoft Outlook
de.ClamWinFreeAntivirus1=ClamWin Free Antivirus
de.ClamWinFreeAntivirus2=ClamWin Antivirus

nl.LanguageName=Dutch
nl.InitializeWizard1=Kies de Installatie Opties
nl.InitializeWizard2=Voor wie moet deze applicatie beschikbaar zijn ?
nl.InitializeWizard3=Gelieve aan te duiden of deze beschikbaar moet zijn voor alle gebruikers, of enkel voor uzelf
nl.InitializeWizard4=&Iedereen die deze computer gebruikt (alle gebruikers)
nl.InitializeWizard5=Enkel voor &mij (
nl.NoOutlookRunning1=U moet Outlook sluiten om ClamWin Free Antivirus te kunnen installeren.
nl.NoOutlookRunning2=Sluit alstublief alle Outlook vensters (via "Bestand->Afsluiten en Afmelden"
nl.NoOutlookRunning3=indien beschikbaar) en klik daarna op Opnieuw, of klik op Annuleren om de installatie te beëindigen.
nl.NoOutlookRunning4=Indien deze boodschap blijft verschijnen na het afsluiten van Outlook,
nl.NoOutlookRunning5=zal u zich in Windows moeten afmelden en daarna opnieuw moeten proberen.
nl.NoOutlookRunning6=De Outlook mail delivery agent draait nog.
nl.NoOutlookRunning7=Als u zonet Outlook heeft afgesloten, wacht dan een paar seconden en klik op Opnieuw.
nl.NoOutlookRunning8=Indien deze boodschap blijft verschijnen, zal u zich in Windows moeten afmelden en daarna opnieuw moeten proberen.
nl.CloseClamWin1=Setup detecteerde dat een vorige versie van de software geïnstalleerd is.
nl.CloseClamWin2=Wil u dit programma nu afsluiten? (Aan te raden)
nl.InitializeSetup1=Setup detecteerde dat een nieuwere versie van het programma is geïnstalleerd.
nl.InitializeSetup2=Setup zal nu afsluiten.
nl.DeInitializeSetup1=Gelieve uw computer opnieuw op te starten om de installatie van ClamWin Free Antivirus te voltooien.
nl.RemoveSetup1=Setup detecteerde dat een vorige versie van de software reeds is geïnstalleerd op de computer. Klik op Ja om deze nu te verwijderen.
nl.DownloadDB1=Download de Virus Database Bestanden. (Niet selecteren indien u verbonden bent met het internet via een Proxy Server)
nl.DownloadDB2=Bezig met het downloaden van de Virus Database Bestanden.
nl.DownloadDB3=Download
nl.CreateDesktop1=Plaats een snelkoppeling op het &bureaublad
nl.CreateDesktop2=Optionele snelkoppelingen:
nl.TypicalInstallation1=Standaard Installatie
nl.CustomInstallation1=Aangepaste Installatie
nl.FullInstallation1=Volledige Installatie
nl.ClamWinSourceCode1=ClamWin Broncode
nl.ClamAVSourceCode1=ClamAV Broncode
nl.InternationalHelpFiles1=Internationale Help Bestanden
nl.RussianHelpFiles1=Russische Help Bestanden
nl.FrenchHelpFiles1=Franse Help Bestanden
nl.DutchHelpFiles1=Nederlandse Help Bestanden
nl.DownloadSourceCode1=Download de Broncode
nl.ClamAVFiles1=ClamAV Bestanden
nl.ClamWinFiles1=ClamWin Bestanden
nl.IntegrationExplorer1=Integratie met de Windows Verkenner
nl.IntegrationOutlook1=Integratie met Microsoft Outlook
nl.ClamWinFreeAntivirus1=ClamWin Free Antivirus
nl.ClamWinFreeAntivirus2=ClamWin Antivirus

fr.LanguageName=French
fr.InitializeWizard1=Sélectionnez les Options d'Installation
fr.InitializeWizard2=Pour qui cette application doit-elle être installée?
fr.InitializeWizard3=Veuillez sélectionner si vous désirez rendre disponible ce logiciel à tous les utilisateurs, ou juste à vous.
fr.InitializeWizard4=&Toute personne qui utilise cet ordinateur (tous les utilisateurs)
fr.InitializeWizard5=Uniquement pour &moi (
fr.NoOutlookRunning1=Vous devez fermer Outlook avant de pouvoir installer ClamWin.
fr.NoOutlookRunning2=Veuillez fermer toutes les fenêtres Outlook (en utilisant "Fichier->Quitter et Fermer la Session"
fr.NoOutlookRunning3=si disponible) and cliquez sur Réessayer, ou cliquez sur Annuler pour quitter l'installation.
fr.NoOutlookRunning4=Si ce message persiste après la fermeture de toutes les fenêtres Outlook,
fr.NoOutlookRunning5=vous pouvez vous déconnecter de Windows, et réessayer.
fr.NoOutlookRunning6=L'agent d'envoi et de réception du courrier Outlook est toujours en marche.
fr.NoOutlookRunning7=Si vous n'avez que récemment fermé Outlook, veuillez patientez quelques secondes et cliquez sur Réessayer.
fr.NoOutlookRunning8=Si ce message persiste, vous pouvez vous déconnecter de Windows, et réessayer.
fr.CloseClamWin1=L'installateur a détecté qu'une version plus ancienne du logiciel est installée.
fr.CloseClamWin2=Voulez-vous fermer le programme maintenant? (Recommandé)
fr.InitializeSetup1=L'installateur a détecté qu'une version plus récente du logiciel est installée.
fr.InitializeSetup2=L'installateur va s'interrompre maintenant.
fr.DeInitializeSetup1=Veuillez redémarrer votre ordinateur pour achever l'installation de l'Antivirus ClamWin.
fr.RemoveSetup1=L'installateur a détecté qu'une version précédente du logiciel est déjà installée sur cet ordinateur. Cliquez sur Oui pour la désinstaller maintenant.
fr.DownloadDB1=Télécharger les Fichiers de Définitions de Virus. (Ne sélectionnez pas si vous vous connectez via un serveur Proxy)
fr.DownloadDB2=Téléchargement des Fichiers de Définitions de Virus en cours
fr.DownloadDB3=Télécharger
fr.CreateDesktop1=Créer une icône sur le &bureau:
fr.CreateDesktop2=Icônes supplémentaires:
fr.TypicalInstallation1=Installation par Défaut
fr.CustomInstallation1=Installation Personnalisée
fr.FullInstallation1=Installation Complète
fr.ClamWinSourceCode1=Code Source de ClamWin
fr.ClamAVSourceCode1=Code Source de ClamAV
fr.InternationalHelpFiles1=Fichiers d'aide internationalisés
fr.RussianHelpFiles1=Fichiers d'aide en russe
fr.FrenchHelpFiles1=Fichiers d'aide en français
fr.DutchHelpFiles1=Fichiers d'aide en hollandais
fr.DownloadSourceCode1=Télécharger le Code Source
fr.ClamAVFiles1=Fichiers ClamAV
fr.ClamWinFiles1=Fichiers ClamWin
fr.IntegrationExplorer1=Intégration avec L'Explorateur Windows
fr.IntegrationOutlook1=Intégration avec Microsoft Outlook
fr.ClamWinFreeAntivirus1=Antivirus Libre et Gratuit ClamWin
fr.ClamWinFreeAntivirus2=Antivirus ClamWin

ru.LanguageName=Russian
ru.InitializeWizard1=Âûáåðèòå âàðèàíò èíñòàëëÿöèè
ru.InitializeWizard1=Âûáåðèòå âàðèàíò èíñòàëëÿöèè
ru.InitializeWizard2=Äëÿ êîãî áóäåò óñòàíîâëåíî ýòî ïðèëîæåíèå?
ru.InitializeWizard3=Ïîæàëóéñòà óêàæèòå, æåëàåòå ëè âû, ÷òîáû ýòà ïðîãðàììà áûëà äîñòóïíà âñåì ïîëüçîâàòåëÿì èëè òîëüêî âàì.
ru.InitializeWizard4=&Ëþáîé ïîëüçîâàòåëü íà ýòîì êîìïüþòåðå (âñå ïîëüçîâàòåëè)
ru.InitializeWizard5=Òîëüêî äëÿ &ìåíÿ (
ru.NoOutlookRunning1=Âû äîëæíû çàêðûòü Outlook ïåðåä óñòàíîâêîé ClamWin.
ru.NoOutlookRunning2=Ïîæàëóéñòà, çàêðîéòå âñå îêíà ñ Outlook (Èñïîëüçóéòå "Ôàéë->Exit and Log off"
ru.NoOutlookRunning3=åñëè äîñòóïíî) è ùåëêíèòå Retry, èëè ùåëêíèòå Cancel äëÿ âûõîäà èç èíñòàëëÿöèè.
ru.NoOutlookRunning4=Åñëè ýòî ñîîáùåíèå ñîõðàíÿåòñÿ ïîñëå òîãî, êàê âû çàêðûëè âñå îêíà Outlook, âàì ìîæåò
ru.NoOutlookRunning5=ïîíàäîáèòñÿ âûéòè èç Windows è ïîïðîáîâàòü çàíîâî.
ru.NoOutlookRunning6=Àãåíò äîñòàâêè ñîîáùåíèé â Outlook åùå ðàáîòàåò.
ru.NoOutlookRunning7=Åñëè âû òîëüêî ÷òî çàêðûëè îêíî Outlook, ïîäîæäèòå íåñêîëüêî ñåêóíä è íàæìèòå Retry.
ru.NoOutlookRunning8=Åñëè ýòî ñîîáùåíèå ñîõðàíÿåòñÿ, âàì ìîæåò ïîòðåáîâàòüñÿ âûéòè èç è ïîïðîáîâàòü çàíîâî.
ru.CloseClamWin1=Ïðîãðàììà óñòàíîâêè îáíàðóæèëà, ÷òî ïðåäóäóùàÿ âåðñèÿ ïðîãðàììíîãî îáåñïå÷åíèÿ áûëà óñòàíîâëåíà.
ru.CloseClamWin2=Õîòèòå ëè âû çàêðûòü ïðîãðàììó ñåé÷àñ? (Ðåêîìåíäóåòñÿ)
ru.InitializeSetup1=Ïðîãðììà óñòàíîâêè îáíàðóæèëà, ÷òî äàííàÿ âåðñèÿ ïðîãðàììíîãî îáåñïå÷åíèÿ óæå óñòàíîâëåíà.
ru.InitializeSetup2=Ïðîãðàììà óñòàíîâêè áóäåò çàâåðøåíà.
ru.DeInitializeSetup1=Ïîæàëóéñòà, ïåðåçàïóñòèòå ñâîé êîìïüþòåð äëÿ çàâåðøåíèÿ óñòàíîâêè àíòèâèðóñà ClamWin Antivirus.
ru.RemoveSetup1=Ïðîãðàììà óñòàíîâêè îáíàðóæèëà ïðåäûäóùóþ âåðñèþ ïðîãðàììû íà ýòîì êîìïüþòåðå. Íàæìèòå Äà äëÿ äåèíñòàëëÿöèè å¸ ñåé÷àñ.
ru.DownloadDB1=Çàãðóçèòü Ôàéëû Âèðóñíîé Áàçû. (Íå îòìå÷àéòå åñëè âû ñîåäèíåíû ÷åðåç ïðîêñè-ñåðâåð)
ru.DownloadDB2=Çàãðóçêà ôàéëîâ âèðóñíîé áàçû.
ru.DownloadDB3=Çàãðóçêà
ru.CreateDesktop1=Ñîçäàòü èêîíêó íà ðàáî÷åì ñòîëå
ru.CreateDesktop2=Äîïîëíèòåëüíûå èêîíêè:
ru.TypicalInstallation1=Òèïè÷íàÿ óñòàíîâêà
ru.CustomInstallation1=Ðó÷íîé âûáîð
ru.FullInstallation1=Ïîëíàÿ óñòàíîâêà
ru.ClamWinSourceCode1=Èñõîäíûå êîäû ClamWin
ru.ClamAVSourceCode1=Èñõîäíûå êîäû ClamAV
ru.InternationalHelpFiles1=Ïåðåâåäåííûå ôàéëû ïîìîùè
ru.RussianHelpFiles1=Ðóññêèé ôàéë ïîìîùè
ru.FrenchHelpFiles1=Ôðàíöóçñêèé ôàéë ïîìîùè
ru.DutchHelpFiles1=Äàòñêèé ôàéë ïîìîùè
ru.DownloadSourceCode1=Çàãðóçèòü èñõîäíûå êîäû
ru.ClamAVFiles1=Ôàéëû ClamAV
ru.ClamWinFiles1=Ôàéëû ClamWin
ru.IntegrationExplorer1=Èíòåãðàöèÿ ñ Windows Explorer
ru.IntegrationOutlook1=Èíòåãðàöèÿ ñ Microsoft Outlook
ru.ClamWinFreeAntivirus1=ClamWin Free Àíòèâèðóñ
ru.ClamWinFreeAntivirus2=ClamWin Àíòèâèðóñ

it.LanguageName=Italian
it.InitializeWizard1=Select Installation Options
it.InitializeWizard2=Who should this application be installed for?
it.InitializeWizard3=Please select whether you wish to make this software available to all users or just yourself.
it.InitializeWizard4=&Anyone who uses this computer (all users)
it.InitializeWizard5=Only for &me (
it.NoOutlookRunning1=You must close Outlook before ClamWin can be installed.
it.NoOutlookRunning2=Please close all Outlook Windows (using "File->Exit and Log off"
it.NoOutlookRunning3=if available) and click Retry, or click Cancel to exit the installation.
it.NoOutlookRunning4=If this message persists after closing all Outlook windows, you may
it.NoOutlookRunning5=need to log off from Windows, and try again.
it.NoOutlookRunning6=The Outlook mail delivery agent is still running.
it.NoOutlookRunning7=If you only recently closed Outlook, wait a few seconds and click Retry.
it.NoOutlookRunning8=If this message persists, you may need to log off from Windows, and try again.
it.CloseClamWin1=The Setup detected a previous version of the software is installed.
it.CloseClamWin2=Would you like to close the program now? (Recommended)
it.InitializeSetup1=Setup detected that a newer version of the software is already installed.
it.InitializeSetup2=Setup will terminate now.
it.DeInitializeSetup1=Please restart your computer in order to complete the installation of ClamWin Antivirus.
it.RemoveSetup1=The Setup detected a previous version of the software is already installed on this computer. Click Yes to uninstall it now.
it.DownloadDB1=Download Virus Database Files. (Do not Select if you connect via a Proxy Server)
it.DownloadDB2=Downloading Virus Database Files.
it.DownloadDB3=Download
it.CreateDesktop1=Create a &desktop icon
it.CreateDesktop2=Additional icons:
it.TypicalInstallation1=Typical Installation
it.CustomInstallation1=Custom Installation
it.FullInstallation1=Full Installation
it.ClamWinSourceCode1=ClamWin Source Code
it.ClamAVSourceCode1=ClamAV Source Code
it.InternationalHelpFiles1=International Help Files
it.RussianHelpFiles1=Russian Help Files
it.FrenchHelpFiles1=French Help Files
it.DutchHelpFiles1=Dutch Help Files
it.DownloadSourceCode1=Download Source Code
it.ClamAVFiles1=ClamAV Files
it.ClamWinFiles1=ClamWin Files
it.IntegrationExplorer1=Integration with Windows Explorer
it.IntegrationOutlook1=Integration with Microsoft Outlook
it.ClamWinFreeAntivirus1=ClamWin Free Antivirus
it.ClamWinFreeAntivirus2=ClamWin Antivirus

es.LanguageName=English
es.InitializeWizard1=Select Installation Options
es.InitializeWizard2=Who should this application be installed for?
es.InitializeWizard3=Please select whether you wish to make this software available to all users or just yourself.
es.InitializeWizard4=&Anyone who uses this computer (all users)
es.InitializeWizard5=Only for &me (
es.NoOutlookRunning1=You must close Outlook before ClamWin can be installed.
es.NoOutlookRunning2=Please close all Outlook Windows (using "File->Exit and Log off"
es.NoOutlookRunning3=if available) and click Retry, or click Cancel to exit the installation.
es.NoOutlookRunning4=If this message persists after closing all Outlook windows, you may
es.NoOutlookRunning5=need to log off from Windows, and try again.
es.NoOutlookRunning6=The Outlook mail delivery agent is still running.
es.NoOutlookRunning7=If you only recently closed Outlook, wait a few seconds and click Retry.
es.NoOutlookRunning8=If this message persists, you may need to log off from Windows, and try again.
es.CloseClamWin1=The Setup detected a previous version of the software is installed.
es.CloseClamWin2=Would you like to close the program now? (Recommended)
es.InitializeSetup1=Setup detected that a newer version of the software is already installed.
es.InitializeSetup2=Setup will terminate now.
es.DeInitializeSetup1=Please restart your computer in order to complete the installation of ClamWin Antivirus.
es.RemoveSetup1=The Setup detected a previous version of the software is already installed on this computer. Click Yes to uninstall it now.
es.DownloadDB1=Download Virus Database Files. (Do not Select if you connect via a Proxy Server)
es.DownloadDB2=Downloading Virus Database Files.
es.DownloadDB3=Download
es.CreateDesktop1=Create a &desktop icon
es.CreateDesktop2=Additional icons:
es.TypicalInstallation1=Typical Installation
es.CustomInstallation1=Custom Installation
es.FullInstallation1=Full Installation
es.ClamWinSourceCode1=ClamWin Source Code
es.ClamAVSourceCode1=ClamAV Source Code
es.InternationalHelpFiles1=International Help Files
es.RussianHelpFiles1=Russian Help Files
es.FrenchHelpFiles1=French Help Files
es.DutchHelpFiles1=Dutch Help Files
es.DownloadSourceCode1=Download Source Code
es.ClamAVFiles1=ClamAV Files
es.ClamWinFiles1=ClamWin Files
es.IntegrationExplorer1=Integration with Windows Explorer
es.IntegrationOutlook1=Integration with Microsoft Outlook
es.ClamWinFreeAntivirus1=ClamWin Free Antivirus
es.ClamWinFreeAntivirus2=ClamWin Antivirus

;cs.LanguageName=Czech
;cs.InitializeWizard1=Vyberte typ instalace
;cs.InitializeWizard2=Pro koho má být ten to program nainstalován?
;cs.InitializeWizard3=Prosím, vyberte zda má být tento program dostupný všem uživatelum nebo pouze Vám.
;cs.InitializeWizard4=&Kdokoliv, kdo používá tento pocítac (všichni uživatelé)
;cs.InitializeWizard5=Pouze pro &me (
;cs.NoOutlookRunning1=Musíte ukoncit Outlook pred instalací ClamWinu.
;cs.NoOutlookRunning2=Zavrete, prosím, všechna okna Outlooku (Pres "Soubor->Ukoncit a Odhlásit"
;cs.NoOutlookRunning3=pokud je to dostupné) a kliknete na Opakovat nebo na Storno pro ukoncení instalace.
;cs.NoOutlookRunning4=Zustane-li tato zpráva po zavrení všech oken Outlooku, budete se
;cs.NoOutlookRunning5=muset odhlásit z Windows a zkusit to znovu.
;cs.NoOutlookRunning6=Agent dorucování zpráv Outlooku stále beží.
;cs.NoOutlookRunning7=Pokud jste práve zavreli Outlook, pockejte pár vterit a kliknete na Opakovat.
;cs.NoOutlookRunning8=Zustane-li tato zpráva, budete se muset odhlásit z Windows a zkusit to znovu.
;cs.CloseClamWin1=Instalátor nalezl nainstalovanou predchozí verzi programu.
;cs.CloseClamWin2=Chcete program ukoncit nyní? (Doporuceno)
;cs.InitializeSetup1=Instalátor nalezi nainstalovanou novejší verzi proogramu.
;cs.InitializeSetup2=Instalátor se nyní ukoncí.
;cs.DeInitializeSetup1=Prosím, zrestartujte svuj pocítac pro dokoncení instalace ClamWin Antiviru.
;cs.RemoveSetup1=Instalátor nalezl na tomto pocítaci nainstalovanou predchozí verzi programu. Kliknete na Ano pro odinstalaci.
;cs.DownloadDB1=Stáhnout soubory databáze viru. (Nevybírejte, pokud jste pripojeni pres proxy server)
;cs.DownloadDB2=Stahuji soubory databází viru.
;cs.DownloadDB3=Stáhnout
;cs.CreateDesktop1=Vytvorit ikonu na &ploše
;cs.CreateDesktop2=Další ikony:
;cs.TypicalInstallation1=Typická instalace
;cs.CustomInstallation1=Vlastní instalace
;cs.FullInstallation1=Plná instalace
;cs.ClamWinSourceCode1=Zdrojové kódy ClamWin
;cs.ClamAVSourceCode1=Zdrojové kódy ClamAV
;cs.InternationalHelpFiles1=Mezinárodní soubory nápovedy
;cs.RussianHelpFiles1=Soubory nápovedy v ruštine
;cs.FrenchHelpFiles1=Soubory nápovedy ve francouzštine
;cs.DutchHelpFiles1=Soubory nápovedy v holandštine
;cs.DownloadSourceCode1=Stáhnout zdrojové kódy
;cs.ClamAVFiles1=ClamAV soubory
;cs.ClamWinFiles1=ClamWin soubory
;cs.IntegrationExplorer1=Integrace do Pruzkumníka Windows
;cs.IntegrationOutlook1=Integrace s Microsoft Outlookem
;cs.ClamWinFreeAntivirus1=ClamWin Free Antivirus
;cs.ClamWinFreeAntivirus2=ClamWin Antivirus

[Code]
var
  //CygwinChecked, CygwinFound: Boolean;
  AllUsers: Boolean;
  SetupCompleted: Boolean;
  Time: String;
  PreviousVersion, ThisVersion: Integer;
  AllUsersPage: TInputOptionWizardPage;

procedure InitializeWizard;
begin
  // Create the pages
  AllUsersPage := CreateInputOptionPage(wpLicense,
    ExpandConstant('{cm:InitializeWizard1}'), ExpandConstant('{cm:InitializeWizard2}'),
    ExpandConstant('{cm:InitializeWizard3}'),
    True, False);
  AllUsersPage.Add(ExpandConstant('{cm:InitializeWizard4}'));
  AllUsersPage.Add(ExpandConstant('{cm:InitializeWizard5}') + GetUserNameString() + ')');


  // Set default values, using settings that were stored last time if possible
  case GetPreviousData('AllUsersMode', '') of
    'anyone': AllUsers := True;
    'onlyme': AllUsers := False;
  end;
  if (AllUsers) then
    AllUsersPage.SelectedValueIndex := 0
  else
    AllUsersPage.SelectedValueIndex := 1;
end;

procedure RegisterPreviousData(PreviousDataKey: Integer);
var
  AllUsersModeStr: String;
begin
  // Store the settings so we can restore them next time
  case AllUsersPage.SelectedValueIndex of
    0: AllUsersModeStr := 'anyone';
    1: AllUsersModeStr := 'onlyme';
  end;
  SetPreviousData(PreviousDataKey, 'AllUsersMode', AllUsersModeStr);
end;

function RemoveSetup(keyname: String): Boolean;
var
	uninstall: String;
	resultcode: Integer;
begin
	if not RegKeyExists(HKEY_LOCAL_MACHINE, keyname) then begin
		Result := True;
		exit;
	end;
	if not RegQueryStringValue(HKEY_LOCAL_MACHINE, keyname, 'UninstallString',  uninstall) then begin
		Result := True;
		exit;
	end;
	if SuppressibleMsgBox(ExpandConstant('{cm:RemoveSetup1}'),
	              mbConfirmation, MB_YESNO, IDYES) = idYes then begin
		Result := Exec(RemoveQuotes(uninstall), ' /SILENT', '', SW_SHOWNORMAL, ewWaitUntilTerminated, resultcode);
	end else begin
		Result := False;
	end;
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
  // Skip pages that shouldn't be shown
  // in win 98/me we don't ask for all users nor we do if an admin is not logged on
  if (PageID = AllUsersPage.ID) then begin
    if (not UsingWinNT()) then
	  Result := True
	else if (not IsAdminLoggedOn()) then begin
	  Result := True;
	end;
  end else
    Result := False;
end;

function NextButtonClick(CurPage: Integer): Boolean;
begin
	// Result := istool_download(CurPage);
	if CurPage = wpFinished then
		SetupCompleted := True
	else if CurPage = AllUsersPage.ID then begin
		case AllUsersPage.SelectedValueIndex of
			0: AllUsers := True;
			1: AllUsers := False;
		end;
		if ((not IsAdminLoggedOn()) and (not AllUsers)) then
			RemoveSetup('SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\ClamWin Antivirus_is1');
	end;
	Result := True
end;


function IsOutlookInstalled() : Boolean;
begin
    Result := RegKeyExists( HKCU, 'Software\Microsoft\Office\Outlook') or
			RegKeyExists( HKLM, 'Software\Microsoft\Office\Outlook') or
			RegKeyExists( HKLM, 'Software\Microsoft\Office\9.0\Outlook') or
			RegKeyExists( HKLM, 'Software\Microsoft\Office\10.0\Outlook') or
			RegKeyExists( HKLM, 'Software\Microsoft\Office\11.0\Outlook');
end;



function CheckNoAppMutex( mutexName: String; closeMsg: String) : Boolean;
begin
    Result := true;
    if Pos('/SUPPRESSMSGBOXES', Uppercase(GetCmdTail())) = 0 then begin
		while Result do begin
			if not CheckForMutexes(mutexName) then
				break;
			Result := MsgBox(closeMsg, mbConfirmation, MB_RETRYCANCEL) = idRetry;
		end;
	end;
end;

function NoOutlookRunning(): Boolean;
var
  closeit: String;
begin
    // Check if Outlook is running.
    closeit:= ExpandConstant('{cm:NoOutlookRunning1}') + #13 + #13 +
              ExpandConstant('{cm:NoOutlookRunning2}') + #13 +
              ExpandConstant('{cm:NoOutlookRunning3}')+ #13 + #13 +
              ExpandConstant('{cm:NoOutlookRunning4}') + #13 +
              ExpandConstant('{cm:NoOutlookRunning5}')
    Result := CheckNoAppMutex('_outlook_mutex_', closeit);
    // Check if MAPISP32.EXE is running - if it is, it implies something is screwey
    // with Outlook.
    if Result then begin
      closeit := ExpandConstant('{cm:NoOutlookRunning6}') + #13 + #13 +
                 ExpandConstant('{cm:NoOutlookRunning7}') + #13 + #13 +
                 ExpandConstant('{cm:NoOutlookRunning8}')
      Result := CheckNoAppMutex('InternetMailTransport', closeit);
    end;
end;

function IsWin9x(): Boolean;
begin
	Result := not UsingWinNT();
end;

function IsXPOrLater(): Boolean;
begin
	Result:= (GetWindowsVersion() >= $05010000);
end;



function IsAllUsers(): Boolean;
begin
	if not UsingWinNT() then
		Result := True
	else
		Result := AllUsers;
end;


procedure CloseClamWin();
var
	path, keyname: String;
	resultcode: Integer;
begin
	keyname := 'SOFTWARE\ClamWin';
	path := ''
	if not RegQueryStringValue(HKEY_CURRENT_USER, keyname, 'path',  path) then begin
		RegQueryStringValue(HKEY_LOCAL_MACHINE, keyname, 'path',  path)
	end;
	if path = '' then begin
		exit;
	end;
	if not CheckForMutexes('ClamWinTrayMutex01') then
        exit;
	if SuppressibleMsgBox(ExpandConstant('{cm:CloseClamWin1}') + #13 +
				 ExpandConstant('{cm:CloseClamWin2}'),
	              mbConfirmation, MB_YESNO, IDYES) = idYes then begin
	    path := RemoveQuotes(path)+'\WClose.exe';
		Exec(path, '', '', SW_SHOWNORMAL, ewWaitUntilTerminated, resultcode);
	end;
end;


function InitializeSetup(): Boolean;
var
	value: Cardinal;
begin
	if (not UsingWinNT()) then
		AllUsers := True
	else
		AllUsers := IsAdminLoggedOn();

	ThisVersion := 886;
	value := 0;
	if not RegQueryDWordValue(HKEY_CURRENT_USER, 'SOFTWARE\Clamwin', 'Version',  value) then begin
		value := 0;
		RegQueryDWordValue(HKEY_LOCAL_MACHINE, 'SOFTWARE\Clamwin', 'Version',  value)
	end;
	PreviousVersion := value;
	if PreviousVersion > ThisVersion then begin
		SuppressibleMsgBox(ExpandConstant('{cm:InitializeSetup1}') + #13 +
				 ExpandConstant('{cm:InitializeSetup2}'), mbError, MB_OK, IDOK);
		Result := False;
		exit;
	end;


	SetupCompleted := False;
	Time := GetDateTimeString('hh:nn', #0, ':') + ':00';
	Result := NoOutlookRunning();
	if Result then CloseClamWin();
end;

procedure DeInitializeSetup();
var
	filename: String;
begin
	DeleteFile(ExpandConstant('{%TEMP|{localappdata}}\clamwin-src.zip'));
	DeleteFile(ExpandConstant('{%TEMP|{localappdata}}\clamav-src.tar.gz'));
	//DeleteFile(ExpandConstant('{%TEMP|{localappdata}}\cygwin-src.tar.bz2'));
	if (SetupCompleted) and (PreviousVersion < 35) then begin
		filename := ExpandConstant('{app}\bin\Tray.exe');
		if (FileExists(filename)) then begin
			DeleteFile(filename);
		end;
		filename := ExpandConstant('{app}\bin\OutlookAddin.exe');
		if (FileExists(filename)) then begin
			DeleteFile(filename);
		end;
		filename := ExpandConstant('{app}\bin\ExplorerShell.dll');
		if (FileExists(filename)) then begin
			RestartReplace(filename, '');
			SuppressibleMsgBox(ExpandConstant('{cm:DeInitializeSetup1}'),
				mbInformation, MB_OK, IDOK);
		end;
	end;
end;


//function NoCygwin(): Boolean;
//begin
//	if not CygWinChecked then begin
//		CygwinFound := RegKeyExists(HKEY_LOCAL_MACHINE, 'SOFTWARE\Cygnus Solutions\Cygwin\mounts v2\/');
//		CygwinChecked := True;
//		Result := not CygwinFound;
//	end
//	else begin
//		Result := not CygwinFound;
//	end
//end;

//function NoCygwinAllUsers(): Boolean;
//begin
//	Result := NoCygWin() and IsAllUsers();
//end;

//function NoCygwinNotAllUsers(): Boolean;
//begin
//	Result := NoCygWin() and not IsAllUsers();
//end;

function
BaseDir(Default: String): String;
begin
	if IsAllUsers() then begin
		Result := ExpandConstant('{pf}');
	end else begin
		Result := ExpandConstant('{userappdata}');
	end;
end;

function CurTime(Default: String): String;
begin
	Result := Time;
end;

function TempDir(Default: String): String;
begin
	Result := GetTempDir();
end;

function CommonProfileDir(Default: String): String;
var
	AppData, Tmp: String;
	i, position: Integer;
begin
	if IsAllUsers() then begin
		AppData := RemoveBackslash(ExpandConstant('{commonappdata}'));
	end else begin
		AppData := ExpandConstant('{userappdata}');
	end;
	// remove last directory from the path (Ususally Application Data)
	Tmp := AppData;
	While True do begin
		i := Pos('\', Tmp);
		if i <> 0 then begin
			Tmp := Copy(Tmp, i + 1, Length(Tmp) - i);
		end else begin
			Break;
		end;
	end;
	position := Length(AppData) - Length(Tmp);
	if position > 0 then begin
		Result := RemoveBackslash(Copy(AppData, 0, position));
	end else begin
		Result := AppData;
	end;
end;


function DesktopDir(Default: String): String;
begin
	if IsAllUsers() then begin
		Result := ExpandConstant('{commondesktop}');
	end else begin
		Result := ExpandConstant('{userdesktop}');
	end;
end;



function IsIniValueEmpty(Param : String): Boolean;
var
	Section, Key, Filename, Val, TempStr, Default : String;
	EndPos: Integer;
begin
	Default := '';
	TempStr := Param;

	EndPos := Pos('*', TempStr);
	Section := Copy(TempStr, 0, EndPos - 1);
	TempStr := Copy(TempStr, EndPos + 1, Length(TempStr) - EndPos)

	EndPos := Pos('*', TempStr);
	Key := Copy(TempStr, 0, EndPos - 1);
	TempStr := Copy(TempStr, EndPos + 1, Length(TempStr) - EndPos)

	Filename := TempStr;

	Val:= Trim(GetIniString(Section, Key, Default, Filename));
	Result := (Val = '')

end;

function IsTemplateConfig(Filename: String): Boolean;
begin
	Result := (not IsWin9x()) and (not FileExists(Filename));
end;
