# Increment ClamWin GUI build counter and generate version files.
# Required -D args:
#   COUNTER_FILE, HEADER_OUT, RC_OUT,
#   BASE_MAJOR, BASE_MINOR, BASE_PATCH
# Optional:
#   BASE_TWEAK=0..N (default 0)
#   INCREMENT=ON|OFF (default ON)

if(NOT DEFINED COUNTER_FILE)
    message(FATAL_ERROR "COUNTER_FILE is required")
endif()
if(NOT DEFINED HEADER_OUT)
    message(FATAL_ERROR "HEADER_OUT is required")
endif()
if(NOT DEFINED RC_OUT)
    message(FATAL_ERROR "RC_OUT is required")
endif()
if(NOT DEFINED BASE_MAJOR OR NOT DEFINED BASE_MINOR OR NOT DEFINED BASE_PATCH)
    message(FATAL_ERROR "BASE_MAJOR, BASE_MINOR and BASE_PATCH are required")
endif()

set(_counter 0)
if(EXISTS "${COUNTER_FILE}")
    file(READ "${COUNTER_FILE}" _raw)
    string(STRIP "${_raw}" _raw)
    if(_raw MATCHES "^[0-9]+$")
        set(_counter "${_raw}")
    endif()
endif()

if(NOT DEFINED BASE_TWEAK)
    set(BASE_TWEAK 0)
endif()

if(NOT DEFINED INCREMENT)
    set(INCREMENT ON)
endif()

if(INCREMENT)
    if(EXISTS "${COUNTER_FILE}")
        file(READ "${COUNTER_FILE}" _raw)
        string(STRIP "${_raw}" _raw)
        if(_raw MATCHES "^[0-9]+$")
            set(_counter "${_raw}")
        endif()
    else()
        set(_counter "${BASE_TWEAK}")
    endif()
    math(EXPR _counter "${_counter} + 1")
else()
    set(_counter "${BASE_TWEAK}")
endif()
set(_version_str "${BASE_MAJOR}.${BASE_MINOR}.${BASE_PATCH}.${_counter}")

# Persist incremented counter.
get_filename_component(_counter_dir "${COUNTER_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${_counter_dir}")
file(WRITE "${COUNTER_FILE}" "${_counter}\n")

# Generate C/C++ header consumed by code.
get_filename_component(_header_dir "${HEADER_OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_header_dir}")
file(WRITE "${HEADER_OUT}"
"/* Auto-generated by increment_clamwin_build_version.cmake. Do not edit. */\n"
"#pragma once\n"
"#define CLAMWIN_VERSION_MAJOR ${BASE_MAJOR}\n"
"#define CLAMWIN_VERSION_MINOR ${BASE_MINOR}\n"
"#define CLAMWIN_VERSION_PATCH ${BASE_PATCH}\n"
"#define CLAMWIN_VERSION_BUILD ${_counter}\n"
"#define CLAMWIN_VERSION_STR \"${_version_str}\"\n")

# Generate RC include consumed by clamwin.rc.
get_filename_component(_rc_dir "${RC_OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_rc_dir}")
file(WRITE "${RC_OUT}"
"/* Auto-generated by increment_clamwin_build_version.cmake. Do not edit. */\n"
"#define CLAMWIN_FILEVERSION ${BASE_MAJOR},${BASE_MINOR},${BASE_PATCH},${_counter}\n"
"#define CLAMWIN_PRODUCTVERSION ${BASE_MAJOR},${BASE_MINOR},${BASE_PATCH},${_counter}\n"
"#define CLAMWIN_FILEVERSION_STR \"${_version_str}\"\n"
"#define CLAMWIN_PRODUCTVERSION_STR \"${_version_str}\"\n")

message(STATUS "ClamWin GUI build version: ${_version_str}")